### ISSUE TITLE
Can you fix the documentation for the methods?

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Setters#29]
https://github.com/linksplatform/Setters/blob/ad4f9285d64ed36be2b44774d230baa03ad4843d/csharp/Platform.Setters/Setter%5BTResult%2C%20TDecision%5D.cs#L33-L96

**Comment by Konard** [comment]
These progress on these comments are tracked in https://github.com/linksplatform/Setters/issues/14
There is no need to fix it, because these comments are not done yet.
